language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env: PHPUNIT=1 BUILD_TEST=0

# Add 7.1 with build testing and 5.2 with only
# basic testing. 5.1 isn't supported on TravisCI
matrix:
  include:
    - php: 7.1
      env: PHPUNIT=1 BUILD_TEST=1
    - php: 5.2
      env: PHPUNIT=0 BUILD_TEST=0

before_install:
  - nvm install 4
  - phpenv config-rm xdebug.ini || return 0

install:
  - phpenv global 7.1 || phpenv global 5.6 || return 0
  - phpenv config-rm xdebug.ini || return 0
  - composer self-update 1.0.0
  - composer self-update
  - composer install

after_install:
  - phpenv global "$TRAVIS_PHP_VERSION"

script:
  - if [ $BUILD_TEST -eq 1 ]; then composer clean && composer format && composer build && git status && git diff-files --quiet --exit-code; fi
  - php ./test/basic.php
