title: Kint, a debugging tool for PHP
description: Zero-setup replacement for var_dump, print_r, and debug_backtrace
authors:
  - Jonathan Vollebregt
  - Rokas Å leinius
baseurl: ""

affix_offset: 240

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

sass:
    style: compressed
